services:
  - type: web
    name: vulnlab-tech
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://localhost:3306/vulnlab_db
      - key: SPRING_DATASOURCE_USERNAME
        value: vulnlab
      - key: SPRING_DATASOURCE_PASSWORD
        value: vulnlab123
